import { AssetURL } from "@/shared/types/misc.types";
import { nanoid } from "nanoid";
import { createEffect, createSignal } from "solid-js"
import { createMutable } from "solid-js/store";
import { Howl } from "howler";

/**
 * Represents an entry for a music track in the music manager.
 *
 * @typedef MusicTrackEntry
 * @property {string} id - A unique identifier for the music track (autogenerated by pushTrack)
 * @property {AssetURL} src - The URL or path to the music track asset.
 * @property {number} [volume] - An optional volume level for the track, where 1.0 is 100% volume.
 */
export type MusicTrackEntry = {
    id: string,
    src: AssetURL,
    volume?: number,
}

const [stack, setStack] = createSignal<MusicTrackEntry[]>([]);
const FADE_DURATION = 1000;
const DEFAULT_VOLUME = 0.5;

let currentHowl: Howl | null = null;
let currentID: string | null = null;

createEffect(() => {
    const top = stack()[stack().length - 1];

    // Stack is empty - fade out current song if one playing...
    if (!top) {
        if (currentHowl) {
          const toFade = currentHowl;
          toFade.fade(toFade.volume(), 0, FADE_DURATION);
          setTimeout(() => {
            toFade.stop();
            if (currentHowl === toFade) currentHowl = null;
          }, FADE_DURATION);
        }
        return;
    }

    const {src, volume} = top;

    // Change in state of the entry itself, but same entry
    if(currentID === top.id && currentHowl) {
        // fade to new volume
        currentHowl.fade(currentHowl.volume(), volume ?? DEFAULT_VOLUME, FADE_DURATION);
        //@ts-expect-error - ._src not in types file, but it exists.
        if(currentHowl._src !== src) { // src changed, fade to new song.
            currentHowl.fade(currentHowl.volume(), 0, FADE_DURATION);
            setTimeout(() => {
                currentHowl?.stop();
                const h = new Howl({src: [src], loop: true, volume: 0});
                h.play();
                h.fade(0, volume ?? DEFAULT_VOLUME, FADE_DURATION);
                currentHowl = h;
            }, FADE_DURATION);
        }
        return;
    }

    // Otherwise it's a new song and we have to fade between them.

    const oldHowl = currentHowl;
    const newHowl = new Howl({src: [src], loop: true, volume: 0});

    newHowl.play();
    newHowl.fade(0, volume ?? DEFAULT_VOLUME, FADE_DURATION);
    currentHowl = newHowl;
    currentID = top.id;

    if(oldHowl) {
        oldHowl.fade(oldHowl.volume(), 0, FADE_DURATION);
        setTimeout(() => oldHowl.stop(), FADE_DURATION);
    }
});



/**
 * The `MusicManager` is responsible for managing a stack of music tracks.
 * It provides methods to add, remove, and manipulate tracks in the stack,
 * as well as access the current state of the stack and the currently playing track
 * 
 * Whatever track at the top of the stack will automatically play on loop.
 *
 * Methods:
 * - `pushTrack(entry: Omit<MusicTrackEntry, 'id'>): MusicTrackEntry`:
 *   Adds a new track to the stack. The track is wrapped in a mutable object
 *   and assigned a unique ID. Returns the newly created mutable object (allowing for reactive updates).
 *
 * - `removeTrack(id: string): void`:
 *   Removes a track from the stack by its ID.
 *
 * - `wipeTracks(): void`:
 *   Clears all tracks from the stack.
 *
 * - `_debug_pop(): void`:
 *   Removes the last track from the stack. This is intended for debugging purposes.
 *
 * Getters:
 * - `stack: MusicTrackEntry[]`:
 *   Returns the current stack of tracks.
 *
 * - `currentTrack: MusicTrackEntry | null`:
 *   Returns the track at the top of the stack (the currently playing track),
 *   or `null` if the stack is empty.
 */
export const MusicManager = {

    // Wrap it mutable and return it so we can reactively update track if desired.
    pushTrack(entry: Omit<MusicTrackEntry, 'id'>): MusicTrackEntry {
        const id = nanoid();
        const track = createMutable({id, ...entry});
        setStack(s => [...s, track]);
        return track;
    },

    removeTrack(id: string) {
        setStack(s => s.filter(t => t.id !== id));
    },

    wipeTracks() {
        setStack([]);
    },

    _debug_pop() {
        setStack(s => s.slice(0, s.length - 1))
    },

    get stack() {
        return stack;
    },

    get currentTrack() {
        return stack()[stack().length - 1] ?? null;
    }
}