import { createSignal } from "solid-js";
import { UILayer } from "./ui-layers.types";
import { ReleaseFn, sceneLock, shellLock, sidebarLock } from "../locks/UILockManager";
import { Optional } from "@/shared/types/misc.types";
import { nanoid } from "nanoid";

const [uilayers, setUILayers] = createSignal<UILayer[]>([]);

const releaseLockByLayer = new Map<string, ReleaseFn>();

/**
 * Adds a new UI layer to the existing stack of UI layers.
 *
 * @param layer - The UI layer to be added to the stack.
 *  - `id` (optional) - A unique identifier for the UI layer. (Will be autogenerated if none provided)
 *  - `component` - A function that returns the JSX element for the UI layer.
 *  - `metaLayer` - (Optional) The meta layer of the UI layer, determining its stacking order.
 *  - `lock` - (Optional) The lock state associated with the UI layer.
 *  - `blockBehind` - (Optional) Whether interactions with layers behind this one are blocked.
 *  - `style` - (Optional) Custom CSS properties for the UI layer (containing div).
 */
export function pushUILayer(layer: Optional<UILayer, 'id'>) {

    const id = layer.id ?? nanoid();

    if(uilayers().some(l => l.id === id)) throw new Error(`Layer with ID ${id} already exists!`);

    setUILayers(prev => [...prev, {...layer, id}]);
    
    let release: ReleaseFn | undefined;

    switch(layer.lock) {
        case 'scene':
            release = sceneLock.acquire();
            break;
        case 'sidebar':
            release = sidebarLock.acquire();
            break;
        case 'all':
            release = shellLock.acquire();
            break;
    }

    if (release) releaseLockByLayer.set(id, release);

    return {
        id,
        popLayer: () => popUILayer(id)
    }
    
}

/**
 * Removes the top UI layer from the stack. If an ID is provided, removes the layer with that ID.
 *
 * @param id - The ID of the UI layer to be removed. If not provided, removes the top layer.
 */
export function popUILayer(id?: string) {
    const idToRelease = id ?? uilayers().at(-1)?.id;
    if (idToRelease == undefined) return;
    releaseLockByLayer.get(idToRelease)?.();
    releaseLockByLayer.delete(idToRelease);
    setUILayers(prev => prev.filter(l => l.id !== idToRelease));
}

/**
 * Clears all UI layers from the stack.
 */
export function clearUILayers() {
    setUILayers([]);
    releaseLockByLayer.forEach(rel => rel());
    releaseLockByLayer.clear();
}

/**
 * Retrieves the current stack of UI layers.
 *
 * @returns A signal containing the current stack of UI layers.
 */
export function getUILayers() {
    return uilayers;
}

